export const webLogo =
  "https://img.freepik.com/premium-vector/simple-minimalist-food-bag-restaurant-delivery-service-logo-design-vector_493994-1029.jpg";

export const img_url =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";
// 9099010285 vivek nj group mutual fund

export const RES_DATA =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.65420&lng=77.23730";

export const RES_MENU =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.65420&lng=77.23730&restaurantId=";

//https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.65420&lng=77.23730

// https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.65420&lng=77.23730&restaurantId=30207

// https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.65420&lng=77.23730&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING

export const ResData = [
  {
    id: "16865",
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "Near Tibetian Market",
    areaName: "Connaught Place",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 3.9,
    quantity: 0,
    price: 200,
  },
  {
    id: "399525",
    name: "KFC",
    cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
    locality: "Kashmere Gate Metro Station",
    areaName: "Kashmiri Gate",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    avgRating: 3.9,
    quantity: 0,
    price: 190,
  },
  {
    id: "253765",
    name: "McDonald's",
    cloudinaryImageId: "535fc9f9c135f7982317bbb6a64a1ffc",
    locality: "Kumar Theatre",
    areaName: "Chandni Chowk",
    costForTwo: "₹400 for two",
    cuisines: ["American"],
    avgRating: 4.2,
    quantity: 0,
    price: 270,
  },
  {
    id: "38925",
    name: "Domino's Pizza",
    cloudinaryImageId: "mdl4tnyc8wbvysqxzhnq",
    locality: "Netaji Subhash Marg",
    areaName: "Daryaganj",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.3,
    quantity: 0,
    price: 230,
  },
  {
    id: "8614",
    name: "Burger King",
    cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    locality: "Connaught Place",
    areaName: "Connaught Place",
    costForTwo: "₹350 for two",
    cuisines: ["Burgers", "American"],
    avgRating: 4.4,
    quantity: 0,
    price: 150,
  },
  {
    id: "128116",
    name: "La Pino'z Pizza",
    cloudinaryImageId: "hgvtyqrxzvpwmbs361er",
    locality: "Kamla Nagar",
    areaName: "Kamla Nagar",
    costForTwo: "₹250 for two",
    cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
    avgRating: 4.1,
    quantity: 0,
    price: 290,
  },
  {
    id: "76225",
    name: "Subway",
    cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
    locality: "Malka Ganj Road",
    areaName: "Kamla Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 4,

    quantity: 0,
    price: 199,
  },
  {
    id: "25823",
    name: "Faasos - Wraps, Rolls & Shawarma",
    cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
    locality: "Connaught Place",
    areaName: "Connaught Place",
    costForTwo: "₹200 for two",
    cuisines: [
      "Kebabs",
      "Fast Food",
      "Snacks",
      "American",
      "Healthy Food",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4.2,
    quantity: 0,
    price: 188,
  },
  {
    id: "169835",
    name: "NIC Ice Creams",
    cloudinaryImageId: "85825a6d74b1059a63a9b688de9f67ce",
    locality: "Beadon Pura",
    areaName: "Karol Bagh",
    costForTwo: "₹120 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.6,
    quantity: 0,
    price: 201,
  },
  {
    id: "62881",
    name: "LunchBox - Meals and Thalis",
    cloudinaryImageId: "qwxytz94vjl3hqbdpeqo",
    locality: "R Block",
    areaName: "Laxmi Nagar",
    costForTwo: "₹200 for two",
    cuisines: [
      "Biryani",
      "North Indian",
      "Punjabi",
      "Healthy Food",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4.3,
    quantity: 0,
    price: 360,
  },
  {
    id: "234208",
    name: "Theobroma",
    cloudinaryImageId: "63dd75492c47fcec191132b8eb299ea5",
    locality: "Swasthya Vihar",
    areaName: "Laxmi Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Bakery", "Desserts"],
    avgRating: 4.6,
    quantity: 0,
    price: 545,
  },
  {
    id: "157768",
    name: "The Good Bowl",
    cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
    locality: "Minto Road",
    areaName: "Connaught Place",
    costForTwo: "₹400 for two",
    cuisines: ["Biryani", "Pastas", "Punjabi", "Desserts", "Beverages"],
    avgRating: 4.3,
    quantity: 0,
    price: 360,
  },
  {
    id: "193479",
    name: "Haldiram's",
    cloudinaryImageId: "hnxwug8pbnby5ftshubz",
    locality: "Kucha Mahajani",
    areaName: "Chandni Chowk",
    costForTwo: "₹350 for two",
    cuisines: ["Sweets", "Snacks", "North Indian"],
    avgRating: 4.3,
    quantity: 0,
    price: 230,
  },
  {
    id: "395804",
    name: "L'Opera",
    cloudinaryImageId: "f60300943f5c60b3b888af6dbfb77ca3",
    locality: "Railway Colony",
    areaName: "Civil Lines",
    costForTwo: "₹600 for two",
    cuisines: ["Bakery", "Cafe", "French", "Desserts", "Continental"],
    avgRating: 4.4,
    quantity: 0,
    price: 170,
  },
  {
    id: "107452",
    name: "Chaayos Chai+Snacks=Relax",
    cloudinaryImageId: "cace805a6ba74137571d0f7ac92302b1",
    locality: "Kashmere Gate Metro Station",
    areaName: "Kashmiri Gate",
    costForTwo: "₹250 for two",
    cuisines: [
      "Bakery",
      "Beverages",
      "Chaat",
      "Desserts",
      "Home Food",
      "Italian",
      "Maharashtrian",
      "Snacks",
      "Street Food",
      "Sweets",
    ],
    avgRating: 4.4,
    quantity: 0,
    price: 100,
  },
  {
    id: "443497",
    name: "EatFit",
    cloudinaryImageId: "a564ace38895abd960157ac2a76aaf2a",
    locality: "Laxmi Narain Street",
    areaName: "Paharganj",
    costForTwo: "₹270 for two",
    cuisines: [
      "Chinese",
      "Healthy Food",
      "Tandoor",
      "Pizzas",
      "North Indian",
      "Thalis",
      "Biryani",
    ],
    avgRating: 4.4,
    quantity: 0,
    price: 299,
  },
  {
    id: "69464",
    name: "Starbucks Coffee",
    cloudinaryImageId: "2418209798927d733a50f5d2ebcc2aee",
    locality: "Connaught Place",
    areaName: "Connaught Place",
    costForTwo: "₹400 for two",
    cuisines: [
      "Beverages",
      "Cafe",
      "Snacks",
      "Desserts",
      "Bakery",
      "Ice Cream",
    ],
    avgRating: 4.2,
    quantity: 0,
    price: 399,
  },
  {
    id: "68578",
    name: "Baskin Robbins - Ice Cream Desserts",
    cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
    locality: "Pandara Road",
    areaName: "Pandara Market",
    costForTwo: "₹150 for two",
    cuisines: ["Ice Cream"],
    avgRating: 4.6,
    quantity: 0,
    price: 450,
  },
  {
    id: "17835",
    name: "Behrouz Biryani",
    cloudinaryImageId: "1a8dfa8b2a73ddf7c6193465ab24c898",
    locality: "Minto Road",
    areaName: "Connaught Place",
    costForTwo: "₹500 for two",
    cuisines: [
      "Biryani",
      "North Indian",
      "Kebabs",
      "Mughlai",
      "Beverages",
      "Desserts",
    ],
    avgRating: 4.3,
    quantity: 0,
    price: 350,
  },
  {
    id: "27797",
    name: "Natural Ice Cream",
    cloudinaryImageId: "huwcwcxol7dnbemjlilq",
    locality: "Connaught Place",
    areaName: "Connaught Place",
    costForTwo: "₹150 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.7,
    quantity: 0,
    price: 200,
  },
];

export const ResCardData = [
  {
    id: "135320512",
    name: "Melts Meal for 1 with Fries - Veg",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Choose your favourite Melts & Fries. Customize your satisfaction.",
    imageId: "77b13d58799f70f670be31e6fe53374e",
    quantity: 1,
    price: 180,
  },
  {
    id: "135320514",
    name: "Melts 3 Course Meal for 1 - Veg",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      'Serves 1 | The perfect "Me Time" meal. Choose your favourite Melts and Fries accompanied with 1 Pepsi PET',
    imageId: "8183f4dc4fd3a1046f1e3334e061c5bf",
    quantity: 1,
    price: 299,
  },
  {
    id: "135320515",
    name: "Melts Meal for 1 with Fries Non-Veg",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Choose your favourite Melts & Fries combo. Customize your satisfaction.",
    imageId: "da8429720566b8992d5c1c6bfeecdd2c",
    quantity: 1,
    price: 220,
  },
  {
    id: "135320517",
    name: "Melts 3 Course Meal for 1 Non-Veg",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      'Serves 1 | The perfect "Me Time" meal. Choose your favourite Melts and Fries accompanied with 1 Pepsi PET',
    imageId: "aecf5902ecf7faa53aa89fda3395c989",
    quantity: 1,
    price: 199,
  },
  {
    id: "135320513",
    name: "Create your Melts Box of 2 - Veg",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Choose any 2 Melts flavour. Double the flavour, double the satisfaction",
    imageId: "e6072e97754de0c6c6030103e0fb50d3",
    quantity: 1,
    price: 399,
  },
  {
    id: "135672212",
    name: "Cheezy Cheese Veg & Loaded BBQ Veg Combo",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Double the satisfaction with Cheezy Cheese Veg & Loaded BBQ Veg Melts.",
    imageId: "0b816322be7e8731246e9492e4b44b84",
    quantity: 1,
    price: 390,
  },
  {
    id: "135320516",
    name: "Create your Melts Box of 2 Non-Veg",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Choose any 2 Melts flavour. Double the flavour, double the satisfaction",
    imageId: "e7620274ab99ba415f3e00480020cb48",
    quantity: 1,
    price: 450,
  },
  {
    id: "135334180",
    name: "Cheezy Cheese Chicken & Loaded BBQ Non-Veg Combo",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Satisfy your non veg cravings with Cheezy Cheese Chicken & Loaded Chicken BBQ Melts.",
    imageId: "3779ffaf02380c80f951a1ed2b90c997",
    quantity: 1,
    price: 510,
  },
  {
    id: "135334181",
    name: "Makhni Paneer & Chicken Tikka Keema Combo",
    category: "New MELTS - Crispy, Cheesy, Loaded",
    description:
      "Serves 1 | Satisfy your desi flavour cravings with Makhni Paneer & Chicken Tikka Keema Melts",
    imageId: "a6c351a9a53ae0c5fa2e5e401b8bf27a",
    quantity: 1,
    price: 490,
  },
  {
    id: "107430382",
    name: "Margherita",
    category: "Veg Pizza",
    description:
      "Serves 1 | Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    imageId: "dpventcrozvfni0lqb10",
    quantity: 1,
    price: 250,
  },
];

export const Item = [
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029845/PC_Creative%20refresh/3D_bau/banners_new/Cakes.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029860/PC_Creative%20refresh/3D_bau/banners_new/Samosas.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029845/PC_Creative%20refresh/3D_bau/banners_new/Burger.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029848/PC_Creative%20refresh/3D_bau/banners_new/Chinese.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029858/PC_Creative%20refresh/3D_bau/banners_new/Rolls.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029852/PC_Creative%20refresh/3D_bau/banners_new/Momos.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029850/PC_Creative%20refresh/3D_bau/banners_new/Dosa.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1675667625/PC_Creative%20refresh/Biryani_2.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029860/PC_Creative%20refresh/3D_bau/banners_new/Sandwich.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029844/PC_Creative%20refresh/3D_bau/banners_new/Chole_Bature.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029858/PC_Creative%20refresh/3D_bau/banners_new/Pure_Veg.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029852/PC_Creative%20refresh/3D_bau/banners_new/Pakodas.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029847/PC_Creative%20refresh/3D_bau/banners_new/Kachori.png",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_160,h_192/v1674029858/PC_Creative%20refresh/3D_bau/banners_new/Shakes.png",
  },
];
